HoneyBadgers.WebApp/Controllers/FavoriteMovieController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using HoneyBadgers.Logic.Services;
using HoneyBadgers.Logic.Services.Interfaces;

namespace HoneyBadgers.WebApp.Controllers
{
    public class FavoriteMovieController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IUserService _userService;

        public FavoriteMovieController(IMovieService movieService, IUserService userService)
        {
            _movieService = movieService;
            _userService = userService;
        }
        // GET: FavoriteMovieController
        public async Task<ActionResult> Index()
        {
            var movies = await _movieService.GetAllMovieShortModel();
            var model = movies.Where(e => e.IsFavorite);
            return View(model);
        }
    }
}

HoneyBadgers.WebApp/Controllers/HomeController.cs
using HoneyBadgers.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Threading.Tasks;
using HoneyBadgers.Logic.Models;
using HoneyBadgers.Logic.Services;
using HoneyBadgers.Logic.Services.Interfaces;

namespace HoneyBadgers.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMovieService _movieService;
        private readonly IUserService _userService;
        private readonly IReviewService _reviewService;

        public HomeController(ILogger<HomeController> logger,
            IMovieService movieService,
            IUserService userService,
            IReviewService reviewService)
        {
            _logger = logger;
            _movieService = movieService;
            _userService = userService;
            _reviewService = reviewService;
        }

        public async Task<IActionResult> Index()
        {
            var modal = new HomeViewModel()
            {
                RecentMovies = await _movieService.GetRecent(),
                FavoriteMovies = _userService.GetFavoriteMovies(),
                RecentReviews = await _reviewService.GetRecentReviews()
            };
            return View(modal);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HoneyBadgers.WebApp/Controllers/MovieController.cs
using System.Collections.Generic;
using HoneyBadgers.Logic.Enums;
using System.Linq;
using System.Threading.Tasks;
using HoneyBadgers.Logic.Models;
using HoneyBadgers.Logic.Services;
using HoneyBadgers.Logic.Services.Interfaces;
using HoneyBadgers.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace HoneyBadgers.WebApp.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IUserService _userService;
        private readonly IReportService _reportService;
        private readonly IMovieSortService _movieSortService;
        public MovieController(IMovieService movieService, IUserService userService, IReportService reportService, IMovieSortService movieSortService)
        {
            _movieService = movieService;
            _userService = userService;
            _reportService = reportService;
            _movieSortService = movieSortService;
        }

        public async Task<IActionResult> Index()
        {

            var movies = await _movieService.GetAllMovieShortModel();
            var model = _movieSortService.SortMovie(movies, SortType.ByMostPopularDescending);
            return View(model);
        }

        public async Task<IActionResult> ShowMovies(SortType sortType, double ratingFrom, double ratingTo)
        {
            var movies = await _movieService.GetAllMovieShortModel();

            if (ratingTo == 0)
            {
                ratingTo = 10;
            }

            movies = _movieSortService.FindMovieWithRatingBetweenLowerHigher(movies, ratingFrom, ratingTo);
            var model = _movieSortService.SortMovie(movies, sortType);

            return PartialView("_MoviePartialView", model);
        }

        // GET: MovieController/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var model = await _movieService.GetDetailMovie(id);
            foreach (var genre in model.Genre)
            {
                await _reportService.AddGenreStats(new CreateGenreStats()
                {
                    GenreName = genre.Name,
                    GenreId = genre.Id
                });
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult AddReview(CreateReviewViewModel textEditor)
        {
            return View("Index");
        }

        public IActionResult AddFavorite(string id)
        {
            _userService.AddFavoriteMovie(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveFavorite(string id)
        {
            _userService.RemoveFavoriteMovie(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult AddFavoriteInDetail(string id)
        {
            _userService.AddFavoriteMovie(id);
            return RedirectToAction("Details", new { ID = id });
        }

        public IActionResult RemoveFavoriteInDetail(string id)
        {
            _userService.RemoveFavoriteMovie(id);
            return RedirectToAction("Details", new { ID = id });
        }
    }
}

HoneyBadgers.WebApp/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using HoneyBadgers.Entity.Models
@using Microsoft.AspNetCore.Html
@model HoneyBadgers.Logic.Models.HomeViewModel
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewData["Title"] = "Home Page";
}

<div class="container mt-3">
    <div class="hb-home-movie-list">
        <div class="hb-home-header">
            <div class="row">
                <div class="col">
                    <h3>Recent Movies</h3>
                </div>
                <div class="col text-end">
                    <a class="hb-home-movie-list__link" asp-area="" asp-controller="Movie" asp-action="Index">View all</a>
                </div>
            </div>
        </div>
        <div id="hbRecentMovies" class="hb-recent-movies d-flex flex-nowrap">
            <div id="recentLeftArrow" class="hb-left-arrow">
                <div class="hb-left-arrow-icon">
                    <i class="fas fa-chevron-left"></i>
                </div>
        
            </div>
            @foreach (var movie in Model.RecentMovies)
            {
                <a asp-controller="Movie" asp-action="Details" asp-route-id="@movie.Id">
                    <div class="hb-recent-movie" style="background-image: linear-gradient(to bottom, transparent 0%, transparent 70%, #000 100%), url( @movie.Poster );">
                        <div class="hb-recent-movie-body">
                            <h5 class="card-title">@movie.Title</h5>
                        </div>
                    </div>
                </a>
                
            }
            <div id="recentRightArrow" class="hb-right-arrow">
                <div class="hb-right-arrow-icon">
                    <i class="fas fa-chevron-right"></i>
                </div>
            </div>
        </div>
    </div>
    @if (SignInManager.IsSignedIn(User))
    {
    <div class="hb-home-movie-list">
        <div class="hb-home-header">
            <div class="row">
                <div class="col">
                    <h3>Your Favorite Movies</h3>
                </div>
                @if (@Model.FavoriteMovies.Count > 0)
                {
                    <div class="col text-end">
                        <a class="hb-home-movie-list__link" asp-area="" asp-controller="FavoriteMovie" asp-action="Index">View all</a>
                    </div>
                }
            </div>
        </div>
        @if (@Model.FavoriteMovies.Count > 0)
        {
    <div id="hbFavoriteMovies" class="hb-favorite-movies d-flex flex-nowrap">
        <div id="favoriteLeftArrow" class="hb-left-arrow">
            <div class="hb-left-arrow-icon">
                <i class="fas fa-chevron-left"></i>
            </div>

        </div>
        @foreach (var movie in Model.FavoriteMovies)
        {
            <a asp-controller="Movie" asp-action="Details" asp-route-id="@movie.Id">
            <div class="hb-favorite-movie" style="background-image: linear-gradient(to bottom, transparent 0%, transparent 70%, #000 100%), url(@movie.Poster);">
                <div class="hb-favorite-movie-body">
                    <h5 class="card-title">@movie.Title</h5>
                </div>
            </div>
            </a>
                    }
                    <div id="favoriteRightArrow" class="hb-right-arrow">
                        <div class="hb-right-arrow-icon">
                            <i class="fas fa-chevron-right"></i>
                        </div>
                    </div>
            </div>
        }
        else
        {
            <div class="hb-empty-movie-list text-center">
                <h4>Oh no ... You haven't added any movies to your favorites yet.</h4>
                <p>You can do this by clicking on the heart in the movie</p>
            </div>
        }
    </div>
    }
    @if (@Model.RecentReviews.Count > 0)
    {
        <div class="hb-home-movie-list">
            <div class="hb-home-header">
                <div class="row">
                    <div class="col">
                        <h3>Recent Reviews</h3>
                    </div>
                </div>
            </div>
            <div class="hb-home-review-list">
                <div class="d-flex flex-row align-items-center">
                    @foreach (var review in Model.RecentReviews)
                    {
                        <div class="hb-home-review">
                            <div class="hb-home-review__image" style="background-image: url( @review.Movie.Poster );"></div>
                            <div class="hb-home-review__text">
                                <div class="hb-home-review__text-header">@review.Movie.Title</div>
                                <div class="hb-home-review__text-title">@review.Title</div>
                                <div class="hb-home-review__text-content">
                                    <div class="hb-home-review__text-body">@(new HtmlString(review.Body))</div>
                                    <div class="hb-home-review__text-read-more">
                                        <a class="mx-1" asp-controller="Review" asp-action="Details" asp-route-id="@review.Id">read more</a>
                                    </div>
                                </div>
                                <div class="hb-home-review__text-user">
                                    <div class="hb-home-review__text-user-avatar">
                                        <i class="fas fa-user-alt"></i>
                                    </div>
                                    <div class="hb-home-review__text-user-name">
                                        @review.User.FirstName @review.User.LastName
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    }
    </div>

@section Scripts{
    <script>
        var recentMovies = document.getElementsByClassName("hb-recent-movie");
        var recentMovieWidth = recentMovies[0].offsetWidth + 8;
        var favoriteMovies = document.getElementsByClassName("hb-favorite-movie");
        var recentMovieContainerWidth = document.getElementById("hbRecentMovies").clientWidth;
        var favoriteMovieContainer = document.getElementById("hbFavoriteMovies");
        var recentScrollPosition = 0;
        var favoriteScrollPosition = 0;
        $("#recentLeftArrow").hide();
        $("#favoriteLeftArrow").hide();
        if (favoriteMovies && favoriteMovieContainer && (recentMovieWidth * favoriteMovies.length) < favoriteMovieContainer.clientWidth) {
            $("#favoriteRightArrow").hide();
        }
        $(function () {
            $("#recentRightArrow").click(function () {
                calculateScrollPosition('right', 'recent', recentMovieWidth * recentMovies.length, recentMovieContainerWidth);
                for (var i = 0; i < recentMovies.length; i++) {
                    recentMovies[i].style.transform = "translateX(" + (recentScrollPosition) + "px)";
                }
            });
            $("#recentLeftArrow").click(function () {
                calculateScrollPosition('left', 'recent', recentMovieWidth * recentMovies.length, recentMovieContainerWidth);
                for (var i = 0; i < recentMovies.length; i++) {
                    recentMovies[i].style.transform = "translateX(" + (recentScrollPosition) + "px)";
                }
            });
            $("#favoriteRightArrow").click(function () {
                calculateScrollPosition('right', 'favorite', recentMovieWidth * favoriteMovies.length, favoriteMovieContainer.clientWidth);
                for (var i = 0; i < favoriteMovies.length; i++) {
                    favoriteMovies[i].style.transform = "translateX(" + (favoriteScrollPosition) + "px)";
                }
            });
            $("#favoriteLeftArrow").click(function () {
                calculateScrollPosition('left', 'favorite', recentMovieWidth * favoriteMovies.length, favoriteMovieContainer.clientWidth);
                for (var i = 0; i < favoriteMovies.length; i++) {
                    favoriteMovies[i].style.transform = "translateX(" + (favoriteScrollPosition) + "px)";
                }
            });
        });
        function calculateScrollPosition(direction, type, moviesLength, containerWidth) {
            var diff;
            var position = type === 'recent' ? recentScrollPosition : favoriteScrollPosition;
            if (direction === 'right') {
                diff = moviesLength - containerWidth + position;
                if (diff > containerWidth) {
                    position -= containerWidth;
                } else {
                    position -= diff;
                }
            }
            if (direction === 'left') {
                diff = position + containerWidth;
                if (diff < 0) {
                    position += containerWidth;
                } else {
                    position -= position;
                }
            }

            if (position === 0) {
                type === 'recent' ? $("#recentLeftArrow").hide() : $("#favoriteLeftArrow").hide();
            } else {
                type === 'recent' ? $("#recentLeftArrow").show() : $("#favoriteLeftArrow").show();
            }
            if (-position + recentMovieContainerWidth === moviesLength) {
                type === 'recent' ? $("#recentRightArrow").hide() : $("#favoriteRightArrow").hide();
            } else {
                type === 'recent' ? $("#recentRightArrow").show() : $("#favoriteRightArrow").show();
            }
            if (type === 'recent') {
                recentScrollPosition = position;
            }
            if (type === 'favorite') {
                favoriteScrollPosition = position;
            }
        }
    </script>
}