HoneyBadgers.WebApp/Controllers/AboutController.cs
using HoneyBadgers.Logic.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Serilog;
using Serilog.Context;

namespace HoneyBadgers.WebApp.Controllers
{
    public class AboutController : Controller
    {
        private readonly ILogger<AboutController> _logger;

        public AboutController(ILogger<AboutController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            
            Log.Information("Section 'About' has been displayed.");
            return View();
        }
    }
}

HoneyBadgers.WebApp/Controllers/GenreController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HoneyBadgers.WebApp.Controllers
{
    public class GenreController : Controller
    {
        // GET: GenraController
        public ActionResult Index()
        {
            return View();
        }

        // GET: GenraController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: GenraController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GenraController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: GenraController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: GenraController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: GenraController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: GenraController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

HoneyBadgers.WebApp/Controllers/MovieController.cs
using System.Collections.Generic;
using HoneyBadgers.Logic.Enums;
using System.Linq;
using System.Threading.Tasks;
using HoneyBadgers.Logic.Models;
using HoneyBadgers.Logic.Services;
using HoneyBadgers.Logic.Services.Interfaces;
using HoneyBadgers.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace HoneyBadgers.WebApp.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IUserService _userService;
        private readonly IReportService _reportService;
        private readonly IMovieSortService _movieSortService;
        public MovieController(IMovieService movieService, IUserService userService, IReportService reportService, IMovieSortService movieSortService)
        {
            _movieService = movieService;
            _userService = userService;
            _reportService = reportService;
            _movieSortService = movieSortService;
        }

        public async Task<IActionResult> Index()
        {

            var movies = await _movieService.GetAllMovieShortModel();
            var model = _movieSortService.SortMovie(movies, SortType.ByMostPopularDescending);
            return View(model);
        }

        public async Task<IActionResult> ShowMovies(SortType sortType, double ratingFrom, double ratingTo)
        {
            var movies = await _movieService.GetAllMovieShortModel();

            if (ratingTo == 0)
            {
                ratingTo = 10;
            }

            movies = _movieSortService.FindMovieWithRatingBetweenLowerHigher(movies, ratingFrom, ratingTo);
            var model = _movieSortService.SortMovie(movies, sortType);

            return PartialView("_MoviePartialView", model);
        }

        // GET: MovieController/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var model = await _movieService.GetDetailMovie(id);
            foreach (var genre in model.Genre)
            {
                await _reportService.AddGenreStats(new CreateGenreStats()
                {
                    GenreName = genre.Name,
                    GenreId = genre.Id
                });
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult AddReview(CreateReviewViewModel textEditor)
        {
            return View("Index");
        }

        public IActionResult AddFavorite(string id)
        {
            _userService.AddFavoriteMovie(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveFavorite(string id)
        {
            _userService.RemoveFavoriteMovie(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult AddFavoriteInDetail(string id)
        {
            _userService.AddFavoriteMovie(id);
            return RedirectToAction("Details", new { ID = id });
        }

        public IActionResult RemoveFavoriteInDetail(string id)
        {
            _userService.RemoveFavoriteMovie(id);
            return RedirectToAction("Details", new { ID = id });
        }
    }
}

HoneyBadgers.WebApp/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Linq;
using HoneyBadgers.Logic.Dto;
using HoneyBadgers.Logic.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace HoneyBadgers.WebApp.Controllers
{
    public class SearchController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IUserService _userService;
        private static string _searchInput;

        public SearchController(IMovieService movieService, IUserService userService)
        {
            _movieService = movieService;
            _userService = userService;
        }

        public IActionResult Index(string search)
        {
            _searchInput = search;
            List<MovieDto> model;

            if (search == null)
            {
                model = _movieService.GetAllMovieShortModel().Result.ToList();
                return View(model);
            }

            model = _movieService.GetAllMovieShortModel().Result.Where(x => x.Title.ToLower().Contains(search.ToLower())).ToList();

            return model.Count == 0 ? View() : View(model);
        }
        public IActionResult AddFavorite(string id)
        {
            _userService.AddFavoriteMovie(id);
            return RedirectToAction("Index", new { search = _searchInput });
        }

        public IActionResult RemoveFavorite(string id)
        {
            _userService.RemoveFavoriteMovie(id);
            return RedirectToAction("Index", new { search = _searchInput });
        }
    }
}

HoneyBadgers.WebApp/Views/Shared/_ChartPartialView.cshtml
@model HoneyBadgers.WebApp.Models.ChartViewModel

@if (@Model != null)
{
    <div class="container" style="position: relative;">
        <div class="row">
            <div class="col">
                <h3>@Model.Title</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-5">
                <p>@Model.Description</p>
            </div>
            <div class="col-7">
                <canvas id="chartData"></canvas>
            </div>
        </div>
    </div>
}

<script>
    var model = @Html.Raw(Json.Serialize(Model));
    console.log(model);
    var title = model['title'];
    var models = model['chartData'];
    var labels = [];
    var dataValues = [];
    for (var i = 0; i < models.length; i++) {
        var obj = models[i];
        labels.push(obj.item1);
        dataValues.push(obj.item2);
    };
    const ctx = document.getElementById('chartData').getContext('2d');
    const myChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: labels,
            datasets: [{
                label: title,
                data: dataValues,
                fill: false,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.6)',
                    'rgba(54, 162, 235, 0.6)',
                    'rgba(255, 206, 86, 0.6)',
                    'rgba(75, 192, 192, 0.6)',
                    'rgba(153, 102, 255, 0.6)',
                    'rgba(255, 159, 64, 0.6)',
                    'rgba(212, 153, 185, 0.6)',
                    'rgba(127, 178, 133, 0.6)',
                    'rgba(54, 117, 45, 0.6)',
                    'rgba(133, 5, 0, 0.6)'
                ],
                hoverOffset: 10
            }]
        },
    });
</script>

HoneyBadgers.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using HoneyBadgers.Entity.Models
@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HoneyBadgers.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/import.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" />
    <link rel="stylesheet" href="~/lib/Font-Awesome/css/regular.min.css">
    <link rel="stylesheet" href="~/lib/Font-Awesome/css/solid.min.css">
    <link rel="stylesheet" href="~/lib/summernote/summernote-bs4.min.css">
    <link rel="stylesheet" href="~/lib/summernote/summernote-lite.min.css">
    <link rel="stylesheet" href="~/lib/summernote/summernote.min.css">
    <script src="~/lib/Chart.js/chart.min.js"></script>
</head>
<body>
    <header class="sticky-top">
        <nav class="hb-navbar hb-navbar-top navbar sticky-top navbar-expand-sm navbar-toggleable-sm box-shadow">
            <div class="container">
                <a class="hb-navbar__logo" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/assets/badger-transparent-logo.png" />
                </a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    HoneyBadgers
                </a>
                <div class="navbar-collapse collapse d-flex justify-content-end">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
        <nav class="hb-navbar hb-navbar-down navbar sticky-top navbar-expand-sm navbar-toggleable-sm box-shadow">
            <div class="container">
                <div class="hb-navbar-container navbar-collapse collapse d-flex justify-content-between">
                    <ul class="hb-navbar-nav navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li>
                                <a class="nav-link" asp-area="" asp-controller="FavoriteMovie" asp-action="Index">Favorite Movies</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="About" asp-action="Index">About</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Manage" asp-action="Index">Manage</a>
                            </li>
                        }
                    </ul>
                    <form class="hb-navbar__search" asp-controller="Search" asp-action="Index" method="get">
                        <div class="input-group" style="background-color: #fff; border-radius: 4px;">
                            <input name="Search" class="hb-navbar__search-input form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="hb-navbar__search-btn btn hb-btn-green" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="hb-main-content mb-4">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="hb-footer border-top footer text-muted">
        <div class="container">
            <div class="row">
                <div class="col">
                    <a class="hb-footer__logo" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/assets/badger-transparent-logo.png" />
                    </a>
                </div>
                <div class="col">

                </div>
                <div class="col mt-2">
                    &copy; 2021 - HoneyBadgers
                </div>
            </div>


        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/summernote/summernote-bs4.min.js"></script>
    <script src="~/lib/summernote/summernote-lite.min.js"></script>
    <script src="~/lib/summernote/summernote.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HoneyBadgers.WebApp/Views/Shared/_MovieHeaderPartialView.cshtml
@using HoneyBadgers.Entity.Models
@using Microsoft.AspNetCore.Identity
@model HoneyBadgers.Logic.Models.DetailMovieViewModel
@inject SignInManager<ApplicationUser> SignInManager

<div class="hb-details-movie__header">
    <div class="container py-3">
        <div class="row">
            <div class="col-md-auto">
                <img height="300" src="@Model.Poster" alt="@Model.Title" />
            </div>
            <div class="col">
                <div class="row">
                    <div class="col">
                        <span class="hb-details-movie__header-type">Movie</span>
                        <h2>@Model.Title</h2>
                        <div class="row" style="padding-left: 15px;">
                            <div class="col-md-auto text-center px-2">@Model.Year</div>
                            <div class="col-md-auto px-1" style="color: #2ba837; font-size: 8px; align-self: center;"><i class="fas fa-circle"></i></div>
                            <div class="col-md-auto text-center px-2">@Model.Runtime</div>
                            <div class="col-md-auto px-1" style="color: #2ba837; font-size: 8px; align-self: center;"><i class="fas fa-circle"></i></div>
                            <div class="col-md-auto text-center px-2">@Model.Language</div>
                            <div class="col-md-auto px-1" style="color: #2ba837; font-size: 8px; align-self: center;"><i class="fas fa-circle"></i></div>
                            <div class="col-md-auto text-center px-2">@Model.Country</div>
                        </div>
                        <div class="d-flex flex-row my-3">
                            @foreach (var genre in Model.Genre)
                            {
                                @*<a class="hb-btn-rounded btn mx-1" asp-controller="Genre" asp-action="List" asp-route-id="@genre.Id">
                                    @genre.Name
                                </a>*@
                                <a class="hb-btn-rounded btn mx-1" href="">
                                    @genre.Name
                                </a>
                            }
                        </div>
                        <div class="hb-details-movie__info">
                            <div class="row">
                                <div class="col-sm-2 text-lowercase">
                                    <label asp-for="Director"></label>
                                </div>
                                <div class="col">
                                    @Model.Director
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-2 text-lowercase">
                                    <label asp-for="Writer"></label>
                                </div>
                                <div class="col">
                                    @Model.Writer
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-2 text-lowercase">
                                    <label asp-for="Actors"></label>
                                </div>
                                <div class="col">
                                    @Model.Actors
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-auto">
                        <div class="text-center mb-4" style="margin-top: 25px;">
                            <div>IMDb Rating</div>
                            <div style="font-size: 25px;"><i style="color: #f6ca2a;" class="fas fa-star mr-2"></i>@Model.ImdbRating</div>
                        </div>
                        <div class="text-center mb-4">
                            <div>Watched</div>
                            <div style="font-size: 25px;"><i style="color: #2ba837;" class="fas fa-chalkboard-teacher mr-2"></i>@Model.ViewsNumber</div>
                        </div>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <div class="text-center mb-4">
                                <div>Favorited</div>
                                <div style="font-size: 25px;">
                                    @if (Model.IsFavorite)
                                    {
                                        <a class="hb-movie__btn-details btn" asp-action="RemoveFavoriteInDetail" asp-route-id="@Model.Id">
                                            <i class="fas fa-heart" style="color: #2ba837; font-size: 35px;"></i>
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="hb-movie__btn-details btn" asp-action="AddFavoriteInDetail" asp-route-id="@Model.Id">
                                            <i class="far fa-heart" style="color: #2ba837; font-size: 35px;"></i>
                                        </a>
                                    }
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HoneyBadgers.WebApp/Views/Shared/_MoviePartialView.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity
@using HoneyBadgers.Entity.Models
@model IEnumerable<HoneyBadgers.Logic.Dto.MovieDto>
@inject SignInManager<ApplicationUser> SignInManager

@foreach (var movie in Model)
{
    <div id="movie-partial-view" class="hb-movie card mb-3">
        <div class="row g-0">
            <div class="col-md-4" style="padding-left: 0px; padding-right: 0px;">
                <img src="@movie.Poster" class="img-fluid rounded-start" alt="@movie.Title">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <div class="row hb-movie__header">
                        <div class="col-md-10">
                            <h6 class="card-title">@movie.Title</h6>
                        </div>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <div class="col-md-2">
                                @if (movie.IsFavorite)
                                {
                                    <a asp-controller="Movie" asp-action="RemoveFavorite" asp-route-id="@movie.Id">
                                        <i class="fas fa-heart"></i>
                                    </a>

                                }
                                else
                                {
                                    <a asp-controller="Movie" asp-action="AddFavorite" asp-route-id="@movie.Id">
                                        <i class="far fa-heart"></i>
                                    </a>
                                }
                            </div>
                        }
                    </div>
                    <div class="hb-movie__option card-text">
                        <label asp-for="@movie.Year"></label>
                        <span>@movie.Year</span>
                    </div>
                    <div class="hb-movie__option card-text">
                        <label asp-for="@movie.Director"></label>
                        <span>@movie.Director</span>
                    </div>
                    <div class="hb-movie__icons card-text d-flex">
                        <div class="hb-movie__rate m-1 d-flex">
                            <i class="fas fa-star"></i>
                            <p class="pl-2 mb-0">@movie.ImdbRating</p>
                        </div>
                        <div class="hb-movie__views m-1 d-flex">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <p class="pl-2 mb-0">@movie.ViewsNumber</p>
                        </div>
                    </div>
                    @if (SignInManager.IsSignedIn(User))
                    {
                    <div class="hb-movie__reviews">
                        @if (@movie.UserReviewId != null)
                        {
                            <a class="hb-movie__views my-2 d-flex" asp-controller="Review" asp-action="Details" asp-route-id="@movie.UserReviewId">
                                <i class="fas fa-feather-alt" style="color: #2ba837; font-size: 23px;"></i>
                                <p class="pl-2 mb-0">You've added review to this movie</p>
                            </a>
                        }
                        else
                        {
                            <a class="hb-movie__views my-2 d-flex" asp-controller="Review" asp-action="Create" asp-route-id="@movie.Id">
                                <i class="fas fa-feather-alt" style="color: #d9d9d9; font-size: 23px;"></i>
                                <p class="pl-2 mb-0">You haven't added a review to this movie yet</p>
                            </a>
                        }
                    </div>
                    }
                    <div class="hb-movie__plot card-text">
                        @movie.Plot
                    </div>
                    <div class="hb-movie__action my-3">
                        <a class="hb-btn btn" role="button" asp-controller="Movie" asp-action="Details" asp-route-id="@movie.Id">View details</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}